The parameter init="pca" cannot be used with metric="precomputed".
ValueError: The parameter init="pca" cannot be used with metric="precomputed".

Changed in version 1.2: The default value changed to "pca".

model = TSNE(n_components=2, random_state=0, metric='precomputed',
                 perplexity=min(len(dist_matrix) - 1, 30), **kwargs)

add back what was the default param initially: init='random'

See also https://github.com/scikit-learn/scikit-learn/issues/18018